### PR TITLE
Feature/UniformField_LayeredSphere

### PR DESCRIPTION
**Pull request by paresula**
Add Uniform Field excitation,
Layered dielectric spheres and layered dielectric spheres
with PEC core and their scattered fields in the static
uniform field.

Other excitations for layered spheres still missing.

### CODE REVIEW

**Review by HoBeZwe — CHANGES_REQUESTED** [review]
Thank you for this nice contribution! However, I think a few things should be fixed:

- Instead of introducing 'VectorField' as a type I would prefer to just go with 'ElectricField' since this is what we are computing after all. Or do you see problems when doing so?
- The type 'ScalarField' I would call 'ScalarPotential' as it sounds more specialized to electrostatics
- Could you supplement for each function the comment with """ ... """
- Could you write small tests 
- Could you supplement the documentation (references and the manual section)

**Comment by paresula** [comment]
Thank you for your remarks, I think I'm on a good way to getting everything fixed. 
However, what would you suggest how to change the "available scattering objects" section? Since now, dielectric and multilayer dielectric spheres are availabe, but not with all the available excitations. 

And I saw that you have prepared documentation sections for implementation details that don't contain anything yet. I would also add this section for the Uniform Field but leave it empty for now, since I don't really know what exactly and to what extent you want to put there - but I can add something there later taking yours as inspiration.

**Comment by HoBeZwe** [comment]
Concerning the "available scattering objects" I would write something like "Dielectric sphere (only for uniform field)" and analogously for the multilayer case.
For the documentation I am fine with adding implementation details after I've done so for the other stuff (which I hopefully find time for in a not so distant future).

**Comment by paresula** [comment]
I hope I have adressed everything, let me know if there is anything else I should change!

**Review by HoBeZwe — APPROVED** [review]

**Pull request merged**
